### ISSUE TITLE
Add other session styles (Raw and Stream)

### ISSUE THREAD

**Issue by mooseman1241** [syvita/solitude#1]
Stream will be important for most communication between eva nodes, as raw and datagrams can fail and don't have any corrective measures to fix this. Datagrams would be useful to have, although for our voice chat implementation we'd probably want to use Raw format with a custom return field to save bandwidth.

**Comment by mooseman1241** [comment]
Probably will focus on Stream for now, as we won't need datagram most likely

**Comment by linden** [comment]
Closed by #8.
